export const weatherImages = {
  'Partly cloudy': require('./partlycloudy.png'),
  'Moderate rain': require('./moderaterain.png'),
  'Patchy rain possible': require('./moderaterain.png'),
  Sunny: require('./sun.png'),
  Clear: require('./sun.png'),
  Overcast: require('./cloud.png'),
  Cloudy: require('./cloud.png'),
  'Light rain': require('./moderaterain.png'),
  'Moderate rain at times': require('./moderaterain.png'),
  'Heavy rain': require('./heavyrain.png'),
  'Heavy rain at times': require('./heavyrain.png'),
  'Moderate or heavy freezing rain': require('./heavyrain.png'),
  'Moderate or heavy rain shower': require('./heavyrain.png'),
  'Moderate or heavy rain with thunder': require('./heavyrain.png'),
  Mist: require('./mist.png'),
  other: require('./moderaterain.png'),
};
